"""add_dashboard_stats_cache

Revision ID: 3638cf52d5d9
Revises: 70323bca3baa
Create Date: 2026-03-26 19:26:51.257607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3638cf52d5d9'
down_revision: Union[str, None] = '70323bca3baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_stats_cache',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('total_commits', sa.Integer(), nullable=False),
    sa.Column('total_additions', sa.Integer(), nullable=False),
    sa.Column('total_deletions', sa.Integer(), nullable=False),
    sa.Column('unique_contributors', sa.Integer(), nullable=False),
    sa.Column('daily_activity', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Daily activity: [{date, commits}]'),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dashboard_stats_cache_org_period', 'dashboard_stats_cache', ['organization_id', 'period'], unique=True)
    op.create_index(op.f('ix_dashboard_stats_cache_organization_id'), 'dashboard_stats_cache', ['organization_id'], unique=False)
    # ### end Alembic commands ###

    # Enable RLS (standard pattern)
    op.execute("ALTER TABLE dashboard_stats_cache ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY dashboard_stats_cache_user_policy ON dashboard_stats_cache
        FOR ALL USING (organization_id IN (
            SELECT organization_id FROM organization_members
            WHERE user_id = current_setting('app.current_user_id')::uuid
        ))
        """
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS dashboard_stats_cache_user_policy ON dashboard_stats_cache")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_stats_cache_organization_id'), table_name='dashboard_stats_cache')
    op.drop_index('ix_dashboard_stats_cache_org_period', table_name='dashboard_stats_cache')
    op.drop_table('dashboard_stats_cache')
    # ### end Alembic commands ###
