"""add_changelog_entries_and_commits_tables

Revision ID: 54f6dd9d1d33
Revises: 8b4e5a9c2fd4
Create Date: 2026-04-02 10:02:48.918766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '54f6dd9d1d33'
down_revision: Union[str, None] = '8b4e5a9c2fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changelog_entries',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('entry_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_changelog_entries_product_date', 'changelog_entries', ['product_id', 'entry_date'], unique=False)
    op.create_index(op.f('ix_changelog_entries_category'), 'changelog_entries', ['category'], unique=False)
    op.create_index(op.f('ix_changelog_entries_product_id'), 'changelog_entries', ['product_id'], unique=False)
    op.create_index(op.f('ix_changelog_entries_title'), 'changelog_entries', ['title'], unique=False)
    op.create_index(op.f('ix_changelog_entries_user_id'), 'changelog_entries', ['user_id'], unique=False)
    op.create_table('changelog_commits',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('changelog_entry_id', sa.UUID(), nullable=False),
    sa.Column('commit_sha', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('commit_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('commit_author', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('committed_at', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['changelog_entry_id'], ['changelog_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_changelog_commits_entry_id', 'changelog_commits', ['changelog_entry_id'], unique=False)
    op.create_index('idx_changelog_commits_sha', 'changelog_commits', ['commit_sha'], unique=False)
    op.create_index('idx_changelog_commits_unique_sha_per_product', 'changelog_commits', ['commit_sha', 'repository_id'], unique=True)
    op.create_index(op.f('ix_changelog_commits_repository_id'), 'changelog_commits', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_changelog_commits_repository_id'), table_name='changelog_commits')
    op.drop_index('idx_changelog_commits_unique_sha_per_product', table_name='changelog_commits')
    op.drop_index('idx_changelog_commits_sha', table_name='changelog_commits')
    op.drop_index('idx_changelog_commits_entry_id', table_name='changelog_commits')
    op.drop_table('changelog_commits')
    op.drop_index(op.f('ix_changelog_entries_user_id'), table_name='changelog_entries')
    op.drop_index(op.f('ix_changelog_entries_title'), table_name='changelog_entries')
    op.drop_index(op.f('ix_changelog_entries_product_id'), table_name='changelog_entries')
    op.drop_index(op.f('ix_changelog_entries_category'), table_name='changelog_entries')
    op.drop_index('idx_changelog_entries_product_date', table_name='changelog_entries')
    op.drop_table('changelog_entries')
    # ### end Alembic commands ###
