"""Add org_api_keys table for partner API authentication

Revision ID: 7cba86c9058a
Revises: 54f6dd9d1d33
Create Date: 2026-04-13 18:56:15.551323

Creates the org_api_keys table for organisation-scoped API keys used by
partner integrations. Includes RLS policies restricting access to org admins.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cba86c9058a'
down_revision: Union[str, None] = '54f6dd9d1d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_api_keys',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_api_keys_created_by_user_id'), 'org_api_keys', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_org_api_keys_key_hash'), 'org_api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_org_api_keys_organization_id'), 'org_api_keys', ['organization_id'], unique=False)
    # ### end Alembic commands ###

    # RLS — org admins can manage keys, no regular member access
    op.execute("ALTER TABLE org_api_keys ENABLE ROW LEVEL SECURITY")

    op.execute("""
        CREATE POLICY org_api_keys_admin_select ON org_api_keys
            FOR SELECT
            USING (is_org_admin(organization_id))
    """)

    op.execute("""
        CREATE POLICY org_api_keys_admin_insert ON org_api_keys
            FOR INSERT
            WITH CHECK (is_org_admin(organization_id))
    """)

    op.execute("""
        CREATE POLICY org_api_keys_admin_update ON org_api_keys
            FOR UPDATE
            USING (is_org_admin(organization_id))
            WITH CHECK (is_org_admin(organization_id))
    """)


def downgrade() -> None:
    # RLS policies
    op.execute("DROP POLICY IF EXISTS org_api_keys_admin_update ON org_api_keys")
    op.execute("DROP POLICY IF EXISTS org_api_keys_admin_insert ON org_api_keys")
    op.execute("DROP POLICY IF EXISTS org_api_keys_admin_select ON org_api_keys")
    op.execute("ALTER TABLE org_api_keys DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_api_keys_organization_id'), table_name='org_api_keys')
    op.drop_index(op.f('ix_org_api_keys_key_hash'), table_name='org_api_keys')
    op.drop_index(op.f('ix_org_api_keys_created_by_user_id'), table_name='org_api_keys')
    op.drop_table('org_api_keys')
    # ### end Alembic commands ###
