"""add repo sync config columns

Revision ID: 8c6ced93b699
Revises: db70ebd8d550
Create Date: 2026-03-19 14:48:52.539039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c6ced93b699'
down_revision: Union[str, None] = 'db70ebd8d550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('sync_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('repositories', sa.Column('sync_branch', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('repositories', sa.Column('sync_path_prefix', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False, server_default=sa.text("'docs/'")))
    op.add_column('repositories', sa.Column('sync_create_pr', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('repositories', sa.Column('sync_doc_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('repositories', sa.Column('last_sync_commit_sha', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True))
    op.add_column('repositories', sa.Column('last_sync_pr_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'last_sync_pr_url')
    op.drop_column('repositories', 'last_sync_commit_sha')
    op.drop_column('repositories', 'sync_doc_filter')
    op.drop_column('repositories', 'sync_create_pr')
    op.drop_column('repositories', 'sync_path_prefix')
    op.drop_column('repositories', 'sync_branch')
    op.drop_column('repositories', 'sync_enabled')
    # ### end Alembic commands ###
